---
# tasks file for nutanix_role_nutanix_dns
- name: Get current DNS configuration
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/cluster/name_servers"
    method: GET
    validate_certs: "{{ role_nutanix_prism_dns_validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    return_content: true
  register: nutanix_dns_current_config

- name: Remove configured DNS server if not provided
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/cluster/name_servers/{{ item }}"
    method: DELETE
    validate_certs: "{{ role_nutanix_prism_dns_validate_certs }}"
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    return_content: true
    status_code: 204
  when:
    - item in nutanix_dns_current_config.json
    - item not in nutanix_dns_server_list
  register: nutanix_dns_remove_missing_entry
  loop: "{{ nutanix_dns_current_config.json }}"

- name: Set DNS server
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/cluster/name_servers"
    method: POST
    validate_certs: "{{ role_nutanix_prism_dns_validate_certs }}"
    body:
      value: "{{ item }}"
    body_format: json
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    return_content: true
    status_code: 200,201
  register: nutanix_dns_update
  loop: "{{ nutanix_dns_server_list }}"
  when: item not in nutanix_dns_current_config.json
