---
# tasks file for role_nutanix_prism_dns
- name: Setup connection to Nutanix API
  ansible.builtin.include_role:
    name: grdavies.role_nutanix_prism_api
  vars:
    role_nutanix_prism_api_host: "{{ role_nutanix_prism_dns_host }}"
    role_nutanix_prism_api_host_username: "{{ role_nutanix_prism_dns_host_username }}"
    role_nutanix_prism_api_host_password: "{{ role_nutanix_prism_dns_host_password }}"
    role_nutanix_prism_api_host_port: "{{ role_nutanix_prism_dns_host_port | default(omit) }}"
    role_nutanix_prism_api_host_validate_certs: "{{ role_nutanix_prism_dns_host_validate_certs | default(omit) }}"
    role_nutanix_prism_api_debug: "{{ role_nutanix_prism_dns_debug | default(omit) }}"

- name: Configure DNS
  ansible.builtin.import_tasks: dns.yml
